# Generated by Django 3.1.1 on 2021-03-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210311_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
