# Generated by Django 3.1.1 on 2021-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
