# Generated by Django 3.1.1 on 2021-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
