# Generated by Django 3.1.1 on 2021-04-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20210428_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='price',
        ),
    ]
