# Generated by Django 3.1.1 on 2021-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_remove_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
