# Generated by Django 3.1.1 on 2021-04-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_photo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='price',
        ),
        migrations.AddField(
            model_name='photo',
            name='bed',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
