# Generated by Django 3.1.1 on 2021-04-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20210428_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='bed',
        ),
    ]
