# Generated by Django 3.1.1 on 2021-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_remove_photo_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
