# Generated by Django 3.1.1 on 2021-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
