# Generated by Django 3.1.1 on 2021-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20210428_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bathroom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='bed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
