# Generated by Django 3.1.1 on 2021-04-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20210428_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='price',
        ),
    ]
