# Generated by Django 3.1.1 on 2021-04-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0017_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
