# Generated by Django 3.1.1 on 2021-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0018_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(default='Apartment', max_length=100),
        ),
    ]
