# Generated by Django 3.1.1 on 2021-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0021_auto_20210429_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(default='house', max_length=100),
        ),
    ]
