# Generated by Django 3.1.1 on 2021-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0022_auto_20210429_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
