# Generated by Django 3.1.1 on 2021-04-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0029_auto_20210430_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
