# Generated by Django 3.1.1 on 2021-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0031_auto_20210430_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
