# Generated by Django 3.1.1 on 2021-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0032_photo_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
