# Generated by Django 2.2.5 on 2021-05-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0034_myrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='places',
            new_name='properties',
        ),
    ]
