# Generated by Django 2.2.5 on 2021-05-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0035_auto_20210510_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='properties',
            new_name='photo',
        ),
    ]
