# Generated by Django 2.2.5 on 2021-05-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0036_auto_20210510_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='photo',
            new_name='property',
        ),
    ]
