# Generated by Django 2.2.5 on 2021-05-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0037_auto_20210510_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='property',
            new_name='photo',
        ),
    ]
