# Generated by Django 3.0.6 on 2021-05-11 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0043_auto_20210511_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='bathroom',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='myrating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
