# Generated by Django 3.0.6 on 2021-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0045_auto_20210512_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='phone',
            field=models.IntegerField(default=1426874),
        ),
    ]
